import 'package:flutter/material.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedUsernameWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedGreentonesgradientbackground_2321483761671Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid1widget/generated/GeneratedRectangle2Widget.dart';

/* Frame Android - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 168.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 492.0,
                child:
                    GeneratedGreentonesgradientbackground_2321483761671Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 326.0,
                top: 242.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 48.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 325.0,
                top: 314.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 48.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 54.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 21.0,
                child: GeneratedUsernameWidget(),
              ),
              Positioned(
                left: 118.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 48.0,
                child: GeneratedGroup12Widget(),
              ),
              Positioned(
                left: 59.0,
                top: 330.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 21.0,
                child: GeneratedPasswordWidget(),
              )
            ]),
      ),
    ));
  }
}
