import 'package:flutter/material.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedAktifitasWidget1.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedFingerprintWidget2.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedAccount_circleWidget3.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedNotifications_noneWidget2.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedProfilWidget1.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedAsn2Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedNotifikasiWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedHourglass_emptyWidget1.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedWELCOMEWidget1.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedPerm_identityWidget1.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedKepalaDinasWidget.dart';
import 'package:flutterapp/simpegapp/generatedandroid3widget/generated/GeneratedEllipse4Widget1.dart';

/* Frame Android - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 197.0,
                child: GeneratedAsn2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: -2.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 245.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 109.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 528.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 123.0,
                top: 189.0,
                right: null,
                bottom: null,
                width: 119.0,
                height: 33.0,
                child: GeneratedWELCOMEWidget1(),
              ),
              Positioned(
                left: 139.0,
                top: 217.0,
                right: null,
                bottom: null,
                width: 84.0,
                height: 18.0,
                child: GeneratedKepalaDinasWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 61.0,
                child: GeneratedRectangle14Widget1(),
              ),
              Positioned(
                left: 310.0,
                top: 616.0,
                right: null,
                bottom: null,
                width: 35.0,
                height: 19.0,
                child: GeneratedProfilWidget1(),
              ),
              Positioned(
                left: 310.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedPerm_identityWidget1(),
              ),
              Positioned(
                left: 233.0,
                top: 616.0,
                right: null,
                bottom: null,
                width: 57.0,
                height: 19.0,
                child: GeneratedNotifikasiWidget1(),
              ),
              Positioned(
                left: 76.0,
                top: 614.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 19.0,
                child: GeneratedAktifitasWidget1(),
              ),
              Positioned(
                left: 247.0,
                top: 591.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedNotifications_noneWidget2(),
              ),
              Positioned(
                left: 85.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedHourglass_emptyWidget1(),
              ),
              Positioned(
                left: 21.0,
                top: 589.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 38.0,
                child: GeneratedGroup1Widget1(),
              ),
              Positioned(
                left: 113.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 117.0,
                child: GeneratedEllipse5Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.18888888888888888;
                  double scaleX = (constraints.maxWidth * percentWidth) / 68.0;

                  double percentHeight = 0.103125;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 66.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.4083333333333333,
                        translateY: constraints.maxHeight * 0.859375,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedEllipse4Widget1())
                  ]);
                }),
              ),
              Positioned(
                left: 157.0,
                top: 557.0,
                right: null,
                bottom: null,
                width: 45.0,
                height: 46.0,
                child: GeneratedFingerprintWidget2(),
              ),
              Positioned(
                left: 113.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 117.0,
                height: 117.0,
                child: GeneratedAccount_circleWidget3(),
              )
            ]),
      ),
    ));
  }
}
